Repository pulumi/pulumi-packet, pull requests merged in 2019-06, with the labels that each got.

#14 Manage CHANGELOG with chg(1)
  CHANGELOG.md
Labels: enhancement

#15 Update pulumi-terraform to 7ace3e9b5f
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/bgpSession.ts
  sdk/nodejs/connect.ts
  sdk/nodejs/device.ts
  sdk/nodejs/ipAttachment.ts
  sdk/nodejs/organization.ts
  sdk/nodejs/portVlanAttachment.ts
  sdk/nodejs/project.ts
  sdk/nodejs/projectSshKey.ts
  sdk/nodejs/provider.ts
  sdk/nodejs/reservedIpBlock.ts
  sdk/nodejs/spotMarketRequest.ts
  sdk/nodejs/sshKey.ts
  sdk/nodejs/vlan.ts
  sdk/nodejs/volume.ts
  sdk/nodejs/volumeAttachment.ts
Labels: area/providers

#17 Addition of constants to make usability better
  CHANGELOG.md
  examples/webserver/index.ts
  resources.go
  sdk/nodejs/billingCycle.ts
  sdk/nodejs/device.ts
  sdk/nodejs/facility.ts
  sdk/nodejs/index.ts
  sdk/nodejs/ipAddressType.ts
  sdk/nodejs/networkType.ts
  sdk/nodejs/operatingSystem.ts
  sdk/nodejs/plan.ts
  sdk/nodejs/tsconfig.json
Labels: enhancement

#19 Update pulumi-terraform to 65eb36cfeb
  go.mod
  go.sum
  sdk/python/README.rst
Labels: area/providers

#21 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required
